### ISSUE TITLE
Create Universal Layout with Footer

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#150]
2 tasks

- [ ] Create universal layout with footer that will be applicable to all UI pages in the Consent Portal
- [ ] Create an OPT-IN layout that uses the universal template + existing header/navigation/page structure

**Expected Outcome(s)**

- [ ] All existing pages look the same, no visual difference
- [ ] There will be 2 layouts, universal vs. opt-in with optional header

**Comment by samrichca** [comment]
revision to this ticket:

register & invite pages do have a navbar, but it's hidden at desktop size. I added the option to hide the navbar at desktop size depending on the page's pathname.

**Comment by b-f-chan** [comment]
@b-f-chan @patrickdsantos - verify on QA

**Comment by patrickdsantos** [comment]
Great work Sam! Footer looks good to me :)

**Comment by patrickdsantos** [comment]
One note however, the mobile view should have a hamburger menu where the "hello" is located. And for tablet view it should show two buttons "Register" and "Login" instead of Hello.


[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2krQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ecec55f965cf5a59b21f9ccf2e07e480e1b8d9d/Screenshot%202023-11-09%20at%2011.04.10%20AM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN20rQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d6ed3d4e7649317a1c6eade633c9b6f1a0a56c78/Screenshot%202023-11-09%20at%2011.05.03%20AM.png)

**Comment by b-f-chan** [comment]
@samrichca can this be closed?
