### ISSUE TITLE
Create Wizard Progress Bar + Title

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#154]
Create reusable UI components for the wizard progress bar + title

**Expected Outcome(s)**

- [x] `Back to Dashboard` link at top is available on the screen
- [x] Title at top of page exists
- [x] White container with the wizard body exists
- [x] Progress bar with div exists
- [x] Different visual states are implemented (step incomplete, complete, etc)

**Comment by alyssadsouza** [comment]
@b-f-chan @patrickdsantos here's the QA link: https://consent-ui.dev.ohcrn.cancercollaboratory.org/en/consent/step-2 and just a few notes:

- You can navigate between the different steps with the URL (like `/step-1` or `/step-3`) since there's no links to next pages right now
- The progress of the user is set to step 1: complete, steps 2-5: incomplete
- The "In Progress" state is for shown for whatever the current step of the page is, so if you're on https://consent-ui.dev.ohcrn.cancercollaboratory.org/en/consent/step-1 it will show step 1 as in progress

Let me know if you have any questions about that!

**Comment by patrickdsantos** [comment]
Amazing work @alyssadsouza , the progress bar looks fantastic on all device sizes! Only one piece of feedback and not sure if this is something that's exclusive to staging but the line between step 1 and 2 is green even when step 1 is set to in progress. 
<img width="525" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVYrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2461e5c3b06991a05f0877e8917158ae215f8bd8/Screenshot%202023-12-21%20at%2010.31.25%20AM.png" alt="Screenshot 2023-12-21 at 10.31.25 AM.png" />

**Comment by patrickdsantos** [comment]
Disregard the feedback! It is indeed a staging thing, no changes needed. Thanks again @alyssadsouza !!

**Comment by b-f-chan** [comment]
Done, closing
