### ISSUE TITLE
Connect Clinician Invite to Registration Flow

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#485]
Connect clinician invite to registration flow

- Fetch Clinician Invite ID from URL query parameter on registration form (i.e. `/register?inviteId=<nanoId>`)
- Then use Invite ID to fetch data from Consent API to prepopulate form for designated fields
- add `inviteId` to `ParticipantRegistrationRequest` (and any corresponding types that handle the Registration request)
- we'll likely need to add a hidden input which gets the `inviteId`, and when we fetch the `inviteId` from the URL query param we fill that value in to a hidden input and it gets passed along with the registration request too

**Comment by mistryrn** [comment]
Updated with information about adding `inviteId` to the types

**Comment by samrichca** [comment]
- Don't account for expired, accepted, or other errors coming from the API
- Don't restrict ages for users with an invite
- Combining this ticket with #476 because this ticket requires participant & guardian to be mutually exclusive

Tasks from #476 
- [ ] Update register form UI (see Patrick's mockups)
  - [ ] On step 2, change the email field to be for 1) guardian email for substitute decision maker or 2) participant email for people registering themselves.
  - [ ] Update phone number field (TBA based on Patrick's mockups)
  - Register flow has no scenarios for guardians.
- [ ] Update register form schema
  - [ ] If guardian consent group: Guardian fields required, participant contact fields must be undefined (not empty)
  - [ ] If participant consent group: Participant contact fields required, guardian fields must be undefined (not empty)
  - [ ] Add specific errors to specific fields, e.g. if guardian consent was selected, and the guardian email is missing, add an error like "guardianMissingInfo" to the guardian email field.
  - [ ] Write unit tests to ensure errors were assigned appropriately. This is to help us know why validation is failing.
    - See participantRegistrationRefinements.spec.ts for testing examples

**Comment by samrichca** [comment]
testing notes:
- go to /en/register?inviteId= and add one of these:
  - adult consent: clmarsvhd000008jngksv
  - young adult consent: clmarsvhd000008jngksa
  - guardian consent of a minor including assent: clmarsvhd000008jngksb
  - guardian consent of a minor: clmarsvhd000008jngksc
  - adult consent substitute decision maker: clmarsvhd000008jngksd
