### ISSUE TITLE
Implement Landing Page Hero

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#57]
Implement landing page hero with these details:

- Link to the OHCRN home site --> https://www.ohcrn.ca
- Link to the participant flow route
- Link to the clinician flow route

**Comment by alyssadsouza** [comment]
This is the current responsive styling based on our three screen sizes (mobile, tablet, desktop). @patrickdsantos let me know if there are changes you'd like me to make, @mistryrn mentioned things feel a bit weird between the tablet and desktop screen sizes so any feedback would be helpful, thanks!
[Screen recording](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXJFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8e380fe03d3aaea811f6212e0318386a8e95e2bb/Screen%20Recording%202023-09-21%20at%2010.19.37%20AM.mp4)

**Comment by patrickdsantos** [comment]
Hey @alyssadsouza reviewed the video again and the sizing between desktop and tablet seem fine. But when you change the page width from 1600px to 2500px things get a bit wonky since the page is so big. 

Is there a way to lock the contents of the page in the position it's in for 1600px? And if the user expands the page to a wider size, the only thing that continues to change is the background while the contents remain centred?

Check out this mock to see what I mean:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDdVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bcba0876ec1abad23c22e00e435864c2e13dc675/RegistryLanding_extra-wide.png)

**Comment by alyssadsouza** [comment]
@patrickdsantos that should be a simple fix! I'll make the changes.

**Comment by b-f-chan** [comment]
@b-f-chan @patrickdsantos - Test in QA before closing

**Comment by patrickdsantos** [comment]
What's the QA link? @alyssadsouza

**Comment by alyssadsouza** [comment]
whoops! forgot to link it: https://consent-ui.dev.ohcrn.cancercollaboratory.org/en

**Comment by patrickdsantos** [comment]
Thanks @alyssadsouza !! Wonderful work here! 

Just two pieces of feedback, not sure if it's related to this ticket or another one but the header is missing two buttons. "Register" and "Login" in place of the Hello at the top right corner. Additionally mobile view should have a hamburger menu. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjIrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--47f46646951d0e5da74f79d85d0f9bf8914f6d65/Screenshot%202023-11-09%20at%2011.04.10%20AM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNisrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--35290c9b107aef677fd13e3aa241256dcda47ad5/Screenshot%202023-11-09%20at%2011.05.03%20AM.png)

If this ticket doesn't cover the header than this is all good on my end! Thank you

**Comment by b-f-chan** [comment]
Done, closing
